# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import skyframe_graph_pb2 as skyframe__graph__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in skyframe_graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SkyframeGraphServiceStub(object):
    """Service for querying the Skyframe in-memory graph.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNode = channel.unary_unary(
                '/skyframe_graph.SkyframeGraphService/GetNode',
                request_serializer=skyframe__graph__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=skyframe__graph__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/skyframe_graph.SkyframeGraphService/GetNodes',
                request_serializer=skyframe__graph__pb2.GetNodesRequest.SerializeToString,
                response_deserializer=skyframe__graph__pb2.GetNodesResponse.FromString,
                _registered_method=True)
        self.GetRoots = channel.unary_stream(
                '/skyframe_graph.SkyframeGraphService/GetRoots',
                request_serializer=skyframe__graph__pb2.GetRootsRequest.SerializeToString,
                response_deserializer=skyframe__graph__pb2.NodeInfo.FromString,
                _registered_method=True)
        self.GetGraphInfo = channel.unary_unary(
                '/skyframe_graph.SkyframeGraphService/GetGraphInfo',
                request_serializer=skyframe__graph__pb2.GetGraphInfoRequest.SerializeToString,
                response_deserializer=skyframe__graph__pb2.GetGraphInfoResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_stream(
                '/skyframe_graph.SkyframeGraphService/ListNodes',
                request_serializer=skyframe__graph__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=skyframe__graph__pb2.NodeInfo.FromString,
                _registered_method=True)
        self.SearchNodes = channel.unary_unary(
                '/skyframe_graph.SkyframeGraphService/SearchNodes',
                request_serializer=skyframe__graph__pb2.SearchNodesRequest.SerializeToString,
                response_deserializer=skyframe__graph__pb2.SearchNodesResponse.FromString,
                _registered_method=True)
        self.RefreshIndex = channel.unary_unary(
                '/skyframe_graph.SkyframeGraphService/RefreshIndex',
                request_serializer=skyframe__graph__pb2.RefreshIndexRequest.SerializeToString,
                response_deserializer=skyframe__graph__pb2.RefreshIndexResponse.FromString,
                _registered_method=True)


class SkyframeGraphServiceServicer(object):
    """Service for querying the Skyframe in-memory graph.
    """

    def GetNode(self, request, context):
        """Look up a single node by its integer ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Look up multiple nodes by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoots(self, request, context):
        """Stream all root nodes (nodes with zero reverse deps).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraphInfo(self, request, context):
        """Return basic graph-level statistics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Stream nodes, optionally filtered by function type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchNodes(self, request, context):
        """Search nodes by substring match on canonical name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshIndex(self, request, context):
        """Re-index the graph. Must be called after a build to refresh the snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkyframeGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=skyframe__graph__pb2.GetNodeRequest.FromString,
                    response_serializer=skyframe__graph__pb2.GetNodeResponse.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=skyframe__graph__pb2.GetNodesRequest.FromString,
                    response_serializer=skyframe__graph__pb2.GetNodesResponse.SerializeToString,
            ),
            'GetRoots': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRoots,
                    request_deserializer=skyframe__graph__pb2.GetRootsRequest.FromString,
                    response_serializer=skyframe__graph__pb2.NodeInfo.SerializeToString,
            ),
            'GetGraphInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphInfo,
                    request_deserializer=skyframe__graph__pb2.GetGraphInfoRequest.FromString,
                    response_serializer=skyframe__graph__pb2.GetGraphInfoResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_stream_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=skyframe__graph__pb2.ListNodesRequest.FromString,
                    response_serializer=skyframe__graph__pb2.NodeInfo.SerializeToString,
            ),
            'SearchNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchNodes,
                    request_deserializer=skyframe__graph__pb2.SearchNodesRequest.FromString,
                    response_serializer=skyframe__graph__pb2.SearchNodesResponse.SerializeToString,
            ),
            'RefreshIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshIndex,
                    request_deserializer=skyframe__graph__pb2.RefreshIndexRequest.FromString,
                    response_serializer=skyframe__graph__pb2.RefreshIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'skyframe_graph.SkyframeGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('skyframe_graph.SkyframeGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkyframeGraphService(object):
    """Service for querying the Skyframe in-memory graph.
    """

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skyframe_graph.SkyframeGraphService/GetNode',
            skyframe__graph__pb2.GetNodeRequest.SerializeToString,
            skyframe__graph__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skyframe_graph.SkyframeGraphService/GetNodes',
            skyframe__graph__pb2.GetNodesRequest.SerializeToString,
            skyframe__graph__pb2.GetNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/skyframe_graph.SkyframeGraphService/GetRoots',
            skyframe__graph__pb2.GetRootsRequest.SerializeToString,
            skyframe__graph__pb2.NodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraphInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skyframe_graph.SkyframeGraphService/GetGraphInfo',
            skyframe__graph__pb2.GetGraphInfoRequest.SerializeToString,
            skyframe__graph__pb2.GetGraphInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/skyframe_graph.SkyframeGraphService/ListNodes',
            skyframe__graph__pb2.ListNodesRequest.SerializeToString,
            skyframe__graph__pb2.NodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skyframe_graph.SkyframeGraphService/SearchNodes',
            skyframe__graph__pb2.SearchNodesRequest.SerializeToString,
            skyframe__graph__pb2.SearchNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skyframe_graph.SkyframeGraphService/RefreshIndex',
            skyframe__graph__pb2.RefreshIndexRequest.SerializeToString,
            skyframe__graph__pb2.RefreshIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
